# Generated by Django 3.0.4 on 2020-04-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='z',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='gamelobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='gamestate.GameLobby'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('interactable', models.BooleanField(default=True)),
                ('gamelobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coins', to='gamestate.GameLobby')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('w', models.FloatField(default=0)),
                ('h', models.FloatField(default=0)),
                ('d', models.FloatField(default=0)),
                ('rx', models.FloatField(default=0)),
                ('ry', models.FloatField(default=0)),
                ('rz', models.FloatField(default=0)),
                ('gamelobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='gamestate.GameLobby')),
            ],
        ),
    ]
