# Generated by Django 3.0.4 on 2020-04-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0002_auto_20200415_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundPlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.FloatField(default=0)),
                ('gamelobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groundplane', to='gamestate.GameLobby')),
            ],
        ),
    ]
