# Generated by Django 3.0.5 on 2020-04-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamestate', '0003_groundplane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayer',
            name='user',
        ),
    ]
