# Generated by Django 3.0.4 on 2020-03-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_matchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
